package com.payneteasy.dapi.acknowledge.cardref.request;

public class CardReferenceSession {

    /**
     * Access token that was given by Merchant's server
     */
    private String accessToken;

    /**
     * Token generated by PaynetEasy
     */
    private String token;

    public CardReferenceSession() {
    }

    public CardReferenceSession(String accessToken, String token) {
        this.accessToken = accessToken;
        this.token = token;
    }

    public String getAccessToken() {
        return accessToken;
    }

    public void setAccessToken(String accessToken) {
        this.accessToken = accessToken;
    }

    public String getToken() {
        return token;
    }

    public void setToken(String token) {
        this.token = token;
    }
}
