package com.payneteasy.dapi.acknowledge.general;

public class InSession {

    /**
     * Access token that was given by Merchant's server
     */
    private String accessToken;

    /**
     * Nonce string that was given by Merchant's server
     */
    private String nonce;

    /**
     * Signature generated with Merchant's secret key
     */
    private String signature;

    /**
     * Token generated by PaynetEasy
     */
    private String token;

    public String getAccessToken() {
        return accessToken;
    }

    public void setAccessToken(String accessToken) {
        this.accessToken = accessToken;
    }

    public String getNonce() {
        return nonce;
    }

    public void setNonce(String nonce) {
        this.nonce = nonce;
    }

    public String getSignature() {
        return signature;
    }

    public void setSignature(String signature) {
        this.signature = signature;
    }

    public String getToken() {
        return token;
    }

    public void setToken(String token) {
        this.token = token;
    }
}
