package com.payneteasy.dapi.acknowledge.general;

import javax.validation.constraints.NotNull;

public class OutSession {

    /**
     * Signature generated with Merchant's secret key
     */
    private String checkSignature;

    /**
     * Nonce string that was given by Merchant's server
     */
    private String nonce;

    /**
     * Token generated by PaynetEasy
     */
    private String token;

    @NotNull
    public String getCheckSignature() {
        return checkSignature;
    }

    public void setCheckSignature(String checkSignature) {
        this.checkSignature = checkSignature;
    }

    @NotNull
    public String getNonce() {
        return nonce;
    }

    public void setNonce(String nonce) {
        this.nonce = nonce;
    }

    @NotNull
    public String getToken() {
        return token;
    }

    public void setToken(String token) {
        this.token = token;
    }
}
